name: CI Java

on:
  pull_request:
  push:
    branches:
      - basic-editing

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 12
        uses: actions/setup-java@v2
        with:
          java-version: '12'
          distribution: 'adopt'
      - name: Build and verify with Maven
        working-directory: ./JHotDraw
        run: mvn --batch-mode --update-snapshots verify
    
    
